project = 4

[repo]
# The GitHub username of the repo owner
owner = "Samk13"
# If the owner is an org, use:
# owner = { type = "organization", login = "piemot" }

# The name of the repository
repo = "gh-projects-migration-test"

[[users]]
trello = "samaa2"
github = "Samk13"

# Map Trello lists to GitHub Project statuses
[[lists]]
list = "USE CASE/USER STORIES->KRAV ğŸ§©"
status = "USE CASE/USER STORIES->KRAV ğŸ§©"
create = true

[[lists]]
list = "BACKLOG ğŸ“• ğŸ“— ğŸ“˜"
status = "BACKLOG ğŸ“• ğŸ“— ğŸ“˜"
create = true

[[lists]]
list = "PÃ…GÃ…RğŸ› "
status = "PÃ…GÃ…RğŸ› "
create = true

[[lists]]
list = "KLART"
status = "KLART"
create = true

[[lists]]
list = "KOMPLETTERA KRAV âœï¸"
status = "KOMPLETTERA KRAV âœï¸"
create = true

[[lists]]
list = "Planerat systemunderhÃ¥ll"
status = "Planerat systemunderhÃ¥ll"
create = true


[[labels]]
trello = "KTH-prod"
github = "KTH-prod"
create = true

[[labels]]
trello = "digital tjÃ¤nst"
github = "digital tjÃ¤nst"
create = true

[[labels]]
trello = "IT-sÃ¤k / non funct. req"
github = "IT-sÃ¤k / non funct. req"
create = true

[[labels]]
trello = "User story 3"
github = "User story 3"
create = true

[[labels]]
trello = "User story 5"
github = "User story 5"
create = true

[[labels]]
trello = "user communication /docs"
github = "user communication /docs"
create = true


[[labels]]
trello = "KTH data repository"
github = "KTH data repository"
create = true


[[labels]]
trello = "UX / UI"
github = "UX / UI"
create = true

[[labels]]
trello = "CERN Ongoing"
github = "CERN Ongoing"
create = true

[[labels]]
trello = "User story 10"
github = "User story 10"
create = true

[[labels]]
trello = "IT-tjÃ¤nster"
github = "IT-tjÃ¤nster"
create = true


[[labels]]
trello = "samarbete andra aktÃ¶rer"
github = "samarbete andra aktÃ¶rer"
create = true

[[labels]]
trello = "SND"
github = "SND"
create = true

[[labels]]
trello = "UI /UX improvement"
github = "UI /UX improvement"
create = true

[[labels]]
trello = "CERN-bug"
github = "CERN-bug"
create = true

[[labels]]
trello = "Devops"
github = "Devops"
create = true